server:
  port: 61747
spring:
  application:
    name: gateway

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:5173
              - http://localhost:3000
              - https://develop.d3buj2sx3ltbzt.amplifyapp.com
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS

      routes:
        - id: aut
          uri: lb://LIBRARY-AUTHENTICATION-SERVICE   # Replace with the logical name of your backend service
          predicates:
            - Path=/api/v1/auth/**
        - id: mailing
          uri: lb://Mail-Notification-Service
          predicates:
            - Path=/api/v1/mailing/**
        - id: upload
          uri: lb://UPLOAD-SERVICE
          predicates:
            - Path=/api/v1/upload/**
